name: "Z-Wave JS UI Proxy"
version: 1.0.2
slug: "z-wave-js-ui-proxy"
description: "Getting access to external Z-wave JS UI from Home Assistant UI"
image: "docker.io/pulpyyyy/zwavejsuiproxy-addon-{arch}"
panel_icon: "mdi:z-wave"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
init: false
options:
  server: "http://192.168.1.222:8091"
  # authenticate: false
  # user: "admin"
  # password: "zwave"
schema:
  server: str
  # authenticate: bool
  # user: str
  # password: password
